version: "3"

services:
  cozzarin_app:
    container_name: cozzarin_davide_app
    build: .
    command: nodemon --watch /usr/src/app -e js app.js
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app            
      - /usr/src/app/node_modules     
    links:
      - "cozzarin_mongo:mongosrv"
    depends_on:
      - cozzarin_mongo

  cozzarin_mongo:
    container_name: cozzarin_davide_mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
